👷 Add startup smoke test for docker image

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,6 +41,18 @@ jobs:
           docker build -t kbudde/bench-metrics:${{ github.sha }} .
           docker tag kbudde/bench-metrics:${{ github.sha }} kbudde/bench-metrics:latest
 
+      - name: docker image smoke test
+        # missing depencies will prevent starting the application.
+        run: |
+          docker run --name benchem -d -it -e BENCH_URL="http://localhost:9090/" kbudde/bench-metrics:latest 
+          sleep 15s
+          docker logs benchem|grep "Benchem started" || {
+            echo "Issue with docker image. Start up log message not found" 
+            echo "## Output: $(docker logs benchem)"
+            exit 1;
+          }
+          docker rm -f benchem || echo "ok"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
